### ISSUE TITLE
calling basicConfig at this level for a library that should be embedded changes all dowstream logs

### ISSUE THREAD

**Issue by erans** [byteskeptical/sftpretty#14]
Calling basicConfig on the top of the file for a library that is embedded into other projects can cause issue.
I suggest you drop it completely specifically because there are no change to it other than setting the default level to INFO.

https://github.com/byteskeptical/sftpretty/blob/ca8e2414ac156276059fcd091cc91e489d856e7d/sftpretty/__init__.py#L22

In our case it added "<level>:<module>" to the start of every log line.

**Comment by byteskeptical** [comment]
I'm not against removing it, but since it is called but default anyway on the first invocation of warning(), error(), info() or debug() if not already called I thought it best to be explicit as it allows for easy switching between levels during development. Can you provide example output of the difference without to get a better idea of the issue?
