### ISSUE TITLE
sftpretty adding console log to root logger

### ISSUE THREAD

**Issue by skroth** [byteskeptical/sftpretty#43]
It appears that here sftpretty is adding a console log handler to the root logger: https://github.com/byteskeptical/sftpretty/blob/root/sftpretty/__init__.py#L252

This is causing our own logging to have duplicate logs for all code running after an sftpretty upload. I can submit a PR that adds a new option to toggle this behavior on or off, if that seems acceptable? Or if the contributors would prefer passing a name to `getLogger` instead of nothing, then users of it can customize sftpretty's logging behavior completely.

**Comment by byteskeptical** [comment]
Yeah this is a remnant of the simple script version this project began as. I think the best course of action is to pass a name to getLogger so user's can have maximum flexibility. I think someone else at @peachfinance pointed this out in a previous PR and was overlooked. Feel free to submit a PR if you have time otherwise I'll do so in a bit.

**Comment by skroth** [comment]
@byteskeptical I commented on the PR referenced but i think we want to also update this line of code: https://github.com/byteskeptical/sftpretty/pull/45/files#r1422981176 I can submit a PR for that
