### ISSUE TITLE
when knowhosts directory doesn't exist. it will keep throwing FileNotFoundError regardless we set hostkeys=None

### ISSUE THREAD

**Issue by mawaliya** [byteskeptical/sftpretty#44]
Currently using 1.1.2 version.
I have been using this way to set the hostkeys to None

```
cnopts.hostkeys = None

```
Apparently it doesnt matter because from the line 99 in `__init__.py` file, it will load from knownhosts.

Currently having an issue when using the client in a container that doesn't have knownhosts directory.
Even though I set hostkeys to None as above, it will try to resolve the default knownhosts which will raise FileNotFoundError.

So the workaround is to set the knownhosts to None, which will automatically set hotkeys to None as well. The only issue for this one is the type, it expects a string so it complains if it's None.

line 99
```
        if knownhosts is not None:
            try:
                self.hostkeys.load(Path(knownhosts).resolve().as_posix())
            except FileNotFoundError:
                # no known_hosts in the default unix location
                raise UserWarning(
                    f'No file or host key found in [{knownhosts}]. '
                    'You will need to explicitly load host keys '
                    '(cnopts.hostkeys.load(filename)) or disable host '
                    'key verification (cnopts.hostkeys = None).'
                )
            else:
                if len(self.hostkeys.items()) == 0:
                    raise HostKeysException('No host keys found!')
        else:
            self.hostkeys = None
```

So,

1. Can we set setting the hostkeys to None taking priority. It will not try to load the default knownhosts directory.
2. Or if not, I think making the knownhosts type to Optional[str] is okay for now.

Thank  you!

**Comment by byteskeptical** [comment]
There are some conflations going on here. I'm not sure what you're trying to achieve exactly but I'm assuming the disabling of host key checking? Is this behavior happening when you pass the CnOpts() object like so:


``` python
import CnOpts, Connection from sftpretty

cnopts = CnOpts(knownhosts=None)
cnopts.hostkeys = None
with Connection('host', username='me', password='pass', cnopts=cnopts):
```

The behavior you describe is similar to what occurs if you try passing or setting CnOpts() on an existing Connection instead of prior too. In my testing I couldn't replicate the behavior could you post a code example? This is perhaps another opportunity to improve documentation as well.

**Comment by mawaliya** [comment]
yes, I was trying to disable host key checking. Almost like the code that you gave above, but I did not put CnOpts knownhosts as None.

```
import CnOpts, Connection from sftpretty

cnopts = CnOpts()
cnopts.hostkeys = None
with Connection('host', username='me', password='pass', cnopts=cnopts):

```
So using the code above, when my machine doesn't have  `~/.ssh/know_hosts` file, it will throw the FileNotFoundError. My assumption was if  we disable host key checking by this line `cnopts.hostkeys = None`, we did not need the know_hosts file.

Maybe my point is, can we not check the known_hosts file if we disable host key checking?

So, maybe removing the `~/.ssh/know_hosts` file temporarily can reproduce this

**Comment by byteskeptical** [comment]
After taking your advice I was able to reproduce the FileNotFoundError if I don't pass `CnOpts(knownhosts=None)` prior to a `Connection()`. For machines that don't have a knownhosts by default and don't pass an alternative this is the equivalent of passing `cnopts.hostkeys = None` for disabling host key checking while avoiding that error. Unfortunately due to the inconsistent behavior on Windows in relation to the interpretation of a user's home directory location depending on severval user configurable options. It becomes difficult to find a universally coherant solution. That as an aside this is still a glaring oversight in not properly explaining this behavaior in documentation. I'll be updating the examples and documentation in the next PR. If you find a way to reproduce the FileNotFoundError while setting knownhosts to None in the meantime or have some improvement suggestions please let me know.
