### ISSUE TITLE
Getting hash results

### ISSUE THREAD

**Issue by heejongkim** [byteskeptical/sftpretty#53]
Hi,

Thanks for the awesome package. I’m sure it’s already serving the community quite well. 

While utilizing it, I want to save the source and destination hash values in a separate log text but i can’t figure out how to accomplish that. I see those values in “fingerprint” log from helper function but I’m not sure I can get those values separately. Again, thank you for the fantastic package. 
-heejong

**Comment by byteskeptical** [comment]
Howdy,

Appreciate the kind words, I'm trying to understand exactly what you're looking to save here. You mention both source and destination as well as the fingerprint. Just want to make sure we are talking about the same thing before I provide possible solutions. The fingerprint refers to the host key verification process and not any specific files being transferred. The value you see in the logs is the results of hashing the remote host key using the sha3_512 algorithm. 

As for file transfers, SFTP in general leans on integrity mechanisms built into the SSH protocol itself. Meaning any corruption that would occur during transfer would immediately throw an error. Because of this despite paramiko having a `SFTPFile.check` implementation of the protocol method[0] available, support is limited to a few obscure server implementations[1]. Notice how this list doesn't include the two most popular server implementations OpenSSH or Dropbear. It also only supports the now very deprecated md5 algorithm so the actual value it provides is questionable at best.

Assuming you actually do want to record remote and local file hashes it is still possible but will not be efficient as it involves tranferring the same file multiple times or using `SSHClient.exec_command` which  depending on server permissions may not be allowed. This is the main reason we provide the hash function but don't implement a version of these by default.

Get:
You can either download the same file using two seperate connections (different IP, proxy, or vpn) and compare both versions locally using the hash function and save the results using a Logger or a simple print statement. Using the same connection is possible but this requires downloading using the `get` method and then using the `exec_command` method to run something like:

`remote_checksum = sftp.exec_command('sha256sum ' + remote file location)`

Put:
You could hash the local file before upload and upon completion then download it using `get` and compare the result to the original. You can also utilize the `exec_command` call, assuming your allowed to, on the server using the same command provided above avoiding the need to download the file again.

Apologies for the long-winded response, let me know if you have any further questions or concerns.


[0] - https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-extensions-00#section-3
[1] - ProFTPD: http://www.proftpd.org/docs/contrib/mod_sftp.html
        Vandyke VShell: https://www.vandyke.com/products/vshell/
        Bitvise SSH Server: https://www.bitvise.com/ssh-server

**Comment by heejongkim** [comment]
Lovely and Fantastic!

Thank you so much for detailed explanation. 
Fortunately, I have a direct access and can execute those commands so I incorporated "sftp.execute" command to get the hash from remote. Also, thanks for sharing the idea of downloading again to check the hash for the integrity when the options are more restrictive. That's very clever!

I hope that other people in the future find your solution useful to meet their needs.

Thank you so much and have a great day.

best,
heejong
